### ISSUE TITLE
Why can the _condition_ part of the for-loop be an identifier? 

### ISSUE THREAD

**Issue by od45pv** [cs-24-sw-4-03/P4-ParserGenerator#15]
I know this is not something you changed, but it might still be a relevant question. Why can the _condition_ part of the for-loop be an identifier? So currently we can write: 

for(int i = 0; i (or any other identifier) ; i = i + 1);

Should the condition not always be a boolean expression?

Same goes for the _update_ part of the for-loop. We can write a for loop like:
for(int i = 0; i < 0; i);

Shouldn't our for-loop be defined as for(identifier | decleration | assignment ; boolExp ; statement) ?

_Originally posted by @adomasciplys in https://github.com/cs-24-sw-4-03/P4-ParserGenerator/pull/13#discussion_r1554996732_

**Comment by EmilChri** [comment]
an identifier can be an boolean expression

**Comment by od45pv** [comment]
Closes #17
